version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - test-network

  redis:
    container_name: redis
    image: redis:5
    ports:
      - "6379:6379"
    restart: always
    networks:
      - test-network

networks:
  test-network: